**Author**: Felipe Matheus <br>
**Start Date** 14/04/2026 <br>
**End Date**: --/--/2025 <br>
**Related Links**:

- Photos taken from deliver of suppliers

**Objective:** 

The objective of this notebook is to do an analysis and a clustering using the data from the percentage of each bag provided by the suppliers in order to create a prototype of a first clusterization and organization of elements.

In [20]:
import os
import sys
import seaborn as sns

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from h2o.automl import H2OAutoML

module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.DataLoader import DataLoader as load
from src.feature_engineering.FeatureEngineering import FeatureEngineering as feng
# from src.visualization.Plots import Plots
# from src.visualization.Visualization import Visualization

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [38]:
SEED = 42

In [ ]:
# proc = Processing()
# plot = Plots()
# feng = FeatureEngineering()
# visu = Visualization()

---
## Load compositions

In [4]:
compositions_path = os.path.abspath(os.path.join('../../data/raw/elements_composition'))
if compositions_path not in sys.path:
    sys.path.append(compositions_path)

from compositions import (
    sac_1A_sac1,
    sac_1A_sac2,
    sac_1B_sac1,
    sac_1B_sac2,
    sac_1B_sac3,
    sac_1B_sac4,
    sac_1B_sac6,
    sac_2N_sac1,
    sac_2N_sac2,
    ALL_SAMPLES,
)

### 1A sac1

In [22]:
flat_1A_sac1 = load.to_flat(sac_1A_sac1, below_limit_zero=True)
flat_1A_sac1

{'Zn': 0.0,
 'Pb': 0.0,
 'Sn': 0.0,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0011,
 'Ni': 0.0,
 'Si': 0.001,
 'Mg': 0.00026,
 'Cr': 0.0,
 'As': 0.00044,
 'Sb': 0.0033,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00081,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00047,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.98,
 'Te': 0.0017}

### 1A sac2

In [23]:
flat_1A_sac2 = load.to_flat(sac_1A_sac2, below_limit_zero=True)
flat_1A_sac2

{'Zn': 0.0,
 'Pb': 0.0,
 'Sn': 0.0,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0011,
 'Ni': 0.0,
 'Si': 0.001,
 'Mg': 0.00026,
 'Cr': 0.0,
 'As': 0.00044,
 'Sb': 0.0033,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00081,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00047,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.98,
 'Te': 0.0019}

### 1B sac1

In [24]:
flat_1B_sac1 = load.to_flat(sac_1B_sac1, below_limit_zero=True)
flat_1B_sac1

{'Zn': 0.0014,
 'Pb': 0.0,
 'Sn': 0.0137,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0012,
 'Ni': 0.0,
 'Si': 0.0011,
 'Mg': 0.00021,
 'Cr': 0.0,
 'As': 0.00043,
 'Sb': 0.0034,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00093,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00051,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.97,
 'Te': 0.002}

### 1B sac2

In [25]:
flat_1B_sac2 = load.to_flat(sac_1B_sac2, below_limit_zero=True)
flat_1B_sac2

{'Zn': 0.0011,
 'Pb': 0.0,
 'Sn': 0.0037,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.00088,
 'Ni': 0.0,
 'Si': 0.00088,
 'Mg': 0.00017,
 'Cr': 0.0,
 'As': 0.00048,
 'Sb': 0.0031,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00095,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00043,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.98,
 'Te': 0.002}

### 1B sac3

In [26]:
flat_1B_sac3 = load.to_flat(sac_1B_sac3, below_limit_zero=True)
flat_1B_sac3

{'Zn': 0.0014,
 'Pb': 0.01,
 'Sn': 0.0033,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.00079,
 'Ni': 0.0,
 'Si': 0.00095,
 'Mg': 0.00021,
 'Cr': 0.0,
 'As': 0.00054,
 'Sb': 0.0034,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00073,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.0004,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.97,
 'Te': 0.0021}

### 1B sac4

In [27]:
flat_1B_sac4 = load.to_flat(sac_1B_sac4, below_limit_zero=True)
flat_1B_sac4

{'Zn': 0.0101,
 'Pb': 0.0053,
 'Sn': 0.0199,
 'P': 0.00026,
 'Mn': 0.0,
 'Fe': 0.0015,
 'Ni': 0.0,
 'Si': 0.0017,
 'Mg': 0.00031,
 'Cr': 0.0,
 'As': 0.00057,
 'Sb': 0.0022,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00096,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00048,
 'Ti': 0.00024,
 'Pt': 0.0,
 'Cu': 99.95,
 'Te': 0.0029}

### 1B sac6

In [28]:
flat_1B_sac6 = load.to_flat(sac_1B_sac6, below_limit_zero=True)
flat_1B_sac6

{'Zn': 0.0,
 'Pb': 0.0,
 'Sn': 0.0195,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0009,
 'Ni': 0.0,
 'Si': 0.00084,
 'Mg': 0.00017,
 'Cr': 0.0,
 'As': 0.0005,
 'Sb': 0.004,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00079,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00043,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.96,
 'Te': 0.0022}

### 2N sac1

In [29]:
flat_2N_sac1 = load.to_flat(sac_2N_sac1, below_limit_zero=True)
flat_2N_sac1

{'Zn': 0.0061,
 'Pb': 0.0332,
 'Sn': 0.006,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0013,
 'Ni': 0.00034,
 'Si': 0.0,
 'Mg': 0.00017,
 'Cr': 0.0,
 'As': 0.00048,
 'Sb': 0.0036,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.0011,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00046,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.94,
 'Te': 0.0021}

### 2N sac2

In [30]:
flat_2N_sac2 = load.to_flat(sac_2N_sac2, below_limit_zero=True)
flat_2N_sac2

{'Zn': 0.0,
 'Pb': 0.302,
 'Sn': 0.0055,
 'P': 0.0,
 'Mn': 0.0,
 'Fe': 0.0012,
 'Ni': 0.0,
 'Si': 0.00085,
 'Mg': 0.00017,
 'Cr': 0.0,
 'As': 0.00054,
 'Sb': 0.0042,
 'Cd': 0.0,
 'Bi': 0.0,
 'Ag': 0.00082,
 'Co': 0.0,
 'Al': 0.0,
 'S': 0.0,
 'Be': 0.0,
 'Zr': 0.0,
 'Au': 0.0,
 'B': 0.00045,
 'Ti': 0.0,
 'Pt': 0.0,
 'Cu': 99.67,
 'Te': 0.002}

---
## All samples — combined DataFrame

In [31]:
df = pd.DataFrame(
    {name: load.to_flat(sample, below_limit_zero=False)
     for name, sample in ALL_SAMPLES.items()}
).T

df

,Zn,Pb,Sn,P,Mn,Fe,Ni,Si,Mg,Cr,...,Al,S,Be,Zr,Au,B,Ti,Pt,Cu,Te
1A sac1,0.0010,0.0003,0.0002,0.00020,0.0004,0.00110,0.00020,0.00100,0.00026,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00047,0.00020,0.002,99.98,0.0017
1A sac2,0.0010,0.0003,0.0002,0.00020,0.0004,0.00110,0.00020,0.00100,0.00026,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00047,0.00020,0.002,99.98,0.0019
1B sac1,0.0014,0.0003,0.0137,0.00020,0.0004,0.00120,0.00020,0.00110,0.00021,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00051,0.00020,0.002,99.97,0.0020
1B sac2,0.0011,0.0003,0.0037,0.00020,0.0004,0.00088,0.00020,0.00088,0.00017,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00043,0.00020,0.002,99.98,0.0020
1B sac3,0.0014,0.0100,0.0033,0.00020,0.0004,0.00079,0.00020,0.00095,0.00021,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00040,0.00020,0.002,99.97,0.0021
1B sac4,0.0101,0.0053,0.0199,0.00026,0.0004,0.00150,0.00020,0.00170,0.00031,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00048,0.00024,0.002,99.95,0.0029
1B sac6,0.0010,0.0003,0.0195,0.00020,0.0004,0.00090,0.00020,0.00084,0.00017,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00043,0.00020,0.002,99.96,0.0022
2N sac1,0.0061,0.0332,0.0060,0.00020,0.0004,0.00130,0.00034,0.00080,0.00017,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00046,0.00020,0.002,99.94,0.0021
2N sac2,0.0010,0.3020,0.0055,0.00020,0.0004,0.00120,0.00020,0.00085,0.00017,0.0003,...,0.0005,0.0002,0.0001,0.0003,0.0006,0.00045,0.00020,0.002,99.67,0.0020

---
# Statistical data generation

In [36]:
sac_1B_sac3

{'Zn': {'val': 0.0014, 'sd': 0.00038, 'rsd': 27.5, 'below_limit': False},
 'Pb': {'val': 0.01, 'sd': 0.00049, 'rsd': 4.9, 'below_limit': False},
 'Sn': {'val': 0.0033, 'sd': 0.00023, 'rsd': 7.1, 'below_limit': False},
 'P': {'val': 0.0002, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Mn': {'val': 0.0004, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Fe': {'val': 0.00079, 'sd': 8e-05, 'rsd': 10.7, 'below_limit': False},
 'Ni': {'val': 0.0002, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Si': {'val': 0.00095, 'sd': 7e-05, 'rsd': 7.1, 'below_limit': False},
 'Mg': {'val': 0.00021, 'sd': 5e-05, 'rsd': 24.8, 'below_limit': False},
 'Cr': {'val': 0.0003, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'As': {'val': 0.00054, 'sd': 0.00011, 'rsd': 19.5, 'below_limit': False},
 'Sb': {'val': 0.0034, 'sd': 0.00014, 'rsd': 4.0, 'below_limit': False},
 'Cd': {'val': 0.0003, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Bi': {'val': 0.0005, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Ag': {'val': 0.00073, 'sd': 5e-05, 'rsd': 7.4, 'below_limit': False},
 'Co': {'val': 0.001, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Al': {'val': 0.0005, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'S': {'val': 0.0002, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Be': {'val': 0.0001, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Zr': {'val': 0.0003, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Au': {'val': 0.0006, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'B': {'val': 0.0004, 'sd': 0.0, 'rsd': 0.6, 'below_limit': False},
 'Ti': {'val': 0.0002, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Pt': {'val': 0.002, 'sd': 0.0, 'rsd': 0.0, 'below_limit': True},
 'Cu': {'val': 99.97, 'sd': 0.0, 'rsd': 0.0, 'below_limit': False},
 'Te': {'val': 0.0021, 'sd': 0.00025, 'rsd': 11.8, 'below_limit': False}}

## Monte Carlo sampling

In [39]:
# below_limit_zero=True  → below-limit elements fixed at 0.0 (no variance injected)
# below_limit_zero=False → below-limit elements sampled from N(val, sd) using the detection-limit value as mean

draws_1B_sac3 = feng.monte_carlo(sac_1B_sac3, n=5000, below_limit_zero=False, seed=SEED)
draws_1B_sac3.describe()

,Zn,Pb,Sn,P,Mn,Fe,Ni,Si,Mg,Cr,...,Al,S,Be,Zr,Au,B,Ti,Pt,Cu,Te
count,5000.000000,5000.000000,5000.000000,5.000000e+03,5.000000e+03,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.0000,...,5.000000e+03,5.000000e+03,5.000000e+03,5000.0000,5000.0000,5.000000e+03,5.000000e+03,5.000000e+03,5.000000e+03,5000.000000
mean,0.001392,0.010000,0.003298,2.000000e-04,4.000000e-04,0.000794,2.000000e-04,0.000951,0.000210,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.002092
std,0.000380,0.000496,0.000230,2.710777e-20,5.421553e-20,0.000080,2.710777e-20,0.000069,0.000051,0.0000,...,1.084311e-19,2.710777e-20,1.355388e-20,0.0000,0.0000,5.421553e-20,2.710777e-20,4.337242e-19,2.842455e-14,0.000248
min,0.000014,0.007849,0.002406,2.000000e-04,4.000000e-04,0.000494,2.000000e-04,0.000703,0.000037,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.001147
25%,0.001137,0.009676,0.003143,2.000000e-04,4.000000e-04,0.000739,2.000000e-04,0.000905,0.000176,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.001924
50%,0.001398,0.009990,0.003293,2.000000e-04,4.000000e-04,0.000794,2.000000e-04,0.000952,0.000211,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.002088
75%,0.001640,0.010329,0.003452,2.000000e-04,4.000000e-04,0.000848,2.000000e-04,0.000997,0.000245,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.002258
max,0.002713,0.011973,0.004255,2.000000e-04,4.000000e-04,0.001046,2.000000e-04,0.001199,0.000394,0.0003,...,5.000000e-04,2.000000e-04,1.000000e-04,0.0003,0.0006,4.000000e-04,2.000000e-04,2.000000e-03,9.997000e+01,0.003121